### ISSUE TITLE
[Bug]: Cannot enable plugin on Android

### ISSUE THREAD

**Issue by dromse** [dromse/obsidian-grind-manager#5]
### What happened?

I cannot activate plugin on my android mobile after plugin update.

### Steps to reproduce

Install new version of plugin 1.0.3 press to activate plugin

### Version

1.0.3

### Obsidian Version

1.5.12

### What platform are you seeing the problem on? (Can be multiple)

Android

### Relevant log output (`Ctrl + Shift + I`)

```shell
app.js:1 Plugin failure: grind-manager ReferenceError: global is not defined
    at anonymous (plugin:grind-manager:15:14458)
    at e.<anonymous> (app.js:1:2226260)
    at app.js:1:237056
    at Object.next (app.js:1:237161)
    at a (app.js:1:235879)
```

### Code of Conduct

- [x] I want to work on this issue

**Comment by dromse** [comment]
This issue was solved by 8a7b7d404036f964a7a4e126a22e1b5b49ef1fcb and available from 1.0.5
